name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    strategy:
      fail-fast: false

      matrix:
        config:
          - name: "ðŸªŸ Windows (MSYS2 UCRT64)"
            os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
            shell: "msys2 {0}"
          - name: "ðŸ§ Linux (GCC)"
            os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            shell: bash
          - name: "ðŸŒ Web (Emscripten)"
            os: ubuntu-latest
            c_compiler: emcc
            cpp_compiler: em++
            shell: bash
            extra_options: -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
            web: true

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies (MSYS2)
      if: matrix.config.shell == 'msys2 {0}'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        install: >-
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-make
          mingw-w64-ucrt-x86_64-SDL2

    - name: Install Dependencies (Linux)
      if: ${{ (runner.os == 'Linux') && (matrix.config.web != true) }}
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsdl2-dev

    - name: Install emsdk
      if: ${{ matrix.config.web }}
      uses: mymindstorm/setup-emsdk@v14

    - name: Configure
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=${{ matrix.config.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.config.c_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        ${{ matrix.config.extra_options }}

    - name: Build
      run: cmake --build build --config Release
